
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 3;
  public static final int FORALL = 20;
  public static final int LOGAND = 43;
  public static final int POWER = 42;
  public static final int MULT = 36;
  public static final int NOTEQUAL = 47;
  public static final int GREATER = 50;
  public static final int LPAREN = 38;
  public static final int CONC = 53;
  public static final int INT = 22;
  public static final int LESS = 48;
  public static final int MINUS = 34;
  public static final int Character = 30;
  public static final int RPAREN = 39;
  public static final int NOT = 45;
  public static final int IN = 6;
  public static final int TDEF = 7;
  public static final int COMMA = 52;
  public static final int BOOL = 25;
  public static final int SEMICOL = 32;
  public static final int FI = 14;
  public static final int DIV = 37;
  public static final int RAT = 24;
  public static final int PLUS = 33;
  public static final int QUOTE = 54;
  public static final int LESSEQ = 49;
  public static final int ASSIGN = 35;
  public static final int MAIN = 5;
  public static final int IF = 13;
  public static final int Float = 27;
  public static final int DOT = 55;
  public static final int EOF = 0;
  public static final int OD = 18;
  public static final int RETURN = 21;
  public static final int EQUAL = 46;
  public static final int error = 1;
  public static final int Integer = 26;
  public static final int DIC = 2;
  public static final int FDEF = 8;
  public static final int VOID = 10;
  public static final int TOP = 4;
  public static final int NOINDEX = 58;
  public static final int LBRCKT = 56;
  public static final int LBRACE = 40;
  public static final int ELSE = 19;
  public static final int READ = 11;
  public static final int LOGOR = 44;
  public static final int WHILE = 15;
  public static final int LET = 59;
  public static final int FLOAT = 23;
  public static final int RBRCKT = 57;
  public static final int RBRACE = 41;
  public static final int THEN = 16;
  public static final int Rational = 29;
  public static final int GREATEREQ = 51;
  public static final int ALIAS = 9;
  public static final int Boolean = 28;
  public static final int PRINT = 12;
  public static final int DO = 17;
  public static final int IDENTIFIER = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIC",
  "SEQ",
  "TOP",
  "MAIN",
  "IN",
  "TDEF",
  "FDEF",
  "ALIAS",
  "VOID",
  "READ",
  "PRINT",
  "IF",
  "FI",
  "WHILE",
  "THEN",
  "DO",
  "OD",
  "ELSE",
  "FORALL",
  "RETURN",
  "INT",
  "FLOAT",
  "RAT",
  "BOOL",
  "Integer",
  "Float",
  "Boolean",
  "Rational",
  "Character",
  "IDENTIFIER",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "ASSIGN",
  "MULT",
  "DIV",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "POWER",
  "LOGAND",
  "LOGOR",
  "NOT",
  "EQUAL",
  "NOTEQUAL",
  "LESS",
  "LESSEQ",
  "GREATER",
  "GREATEREQ",
  "COMMA",
  "CONC",
  "QUOTE",
  "DOT",
  "LBRCKT",
  "RBRCKT",
  "NOINDEX",
  "LET"
  };
}

